github:
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
custom:
  - https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/donate.md
