"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const danmaku_converter_1 = require("./danmaku-converter");
const fs_1 = require("fs");
const config = danmaku_converter_1.getDefaultDanmakuConverterConfig('test');
const input = 'test.xml';
const output = 'test.ass';
const converter = new danmaku_converter_1.DanmakuConverter(config);
const xml = fs_1.readFileSync(input, { encoding: 'utf8' });
const ass = converter.convertToAssDocument(xml).generateAss();
fs_1.writeFileSync(output, ass);
