name: Bug 反馈
description: 功能运行不正常 / 失效
body:
  - type: markdown
    attributes:
      value: |
        默认您已阅读 [Issues 须知](https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/issue-rules.md)
        请勿重复发起, 发之前记得看下[置顶问题 (Pinned issues)](https://github.com/the1812/Bilibili-Evolved/issues) (如果有的话), 以及[常见问题解答](https://github.com/the1812/Bilibili-Evolved/discussions/1301)
  - type: textarea
    id: feature
    attributes:
      label: 对应功能
      description: |
        (指本脚本的某项具体功能, 不是指 b 站的) 可以在设置中尝试开启 / 关闭某项功能来排查. 最好能附上功能的 Commit 值 (在设置里功能选项的底部). 
        <img src="https://user-images.githubusercontent.com/26504152/152666017-8a5acabc-2ad1-47ef-b0a2-cd5c54c867ab.jpg" width="400">
        请注意: 以下功能已不再维护 (不再修复 bug 和添加新功能), 但是你仍然可以为其提供 Pull Request.
        - 直播间自动抽奖
        - 默认播放器模式
        - 播放器置顶
        - 播放器定位
      placeholder: 请输入
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 如何重现此问题, 在哪个页面里出现这个问题, 比如视频相关的可以提供一下 av / BV 号
      placeholder: 请输入
    validations:
      required: true
  - type: input
    id: script-version
    attributes:
      label: 脚本版本
      description: 可在设置面板的关于弹窗中找到脚本版本信息
      placeholder: 请输入
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: 浏览器版本
      description: 可在浏览器的关于页面中找到浏览器版本信息
      placeholder: 请输入
    validations:
      required: true
  - type: input
    id: player-version
    attributes:
      label: 播放器版本
      description: |
        在 b 站播放器上右键可以看到播放器版本号, 大于 3 的别反馈视频相关功能了, 去 [#3187](https://github.com/the1812/Bilibili-Evolved/issues/3187) 里有. 如果是 2, 还要确认下是不是新版播放页, 需要返回旧版才能使用脚本功能. (辨认方法可参考 [#3384](https://github.com/the1812/Bilibili-Evolved/discussions/3384))
      placeholder: 请输入
    validations:
      required: true
  - type: dropdown
    id: player-codec
    attributes:
      label: 播放策略
      description: 在 b 站播放器设置 - 更多播放设置 里可以看到播放策略
      options:
        - 默认
        - AV1
        - HEVC
        - AVC
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 错误信息
      description: |
        脚本直接报告的错误信息, 或者浏览器开发者工具 (F12 或 Ctrl+Shift+I 召唤) 里 Console / 控制台 一栏的输出, 在过滤里填入 `bilibili evolved`, 剩下的信息就可以粘贴过来, 太长的话可以截图放下面. <br><img width="400" src="https://user-images.githubusercontent.com/26504152/173189611-f1e9e46a-a31d-4d21-a95a-5771e16372dd.png">
        如果是近期出问题, 并且其中包含 `couldn't load @require from URL 'https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js'`, 请看 [#3337](https://github.com/the1812/Bilibili-Evolved/issues/3337) 的解答
      render: shell
      placeholder: 请输入
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 附加截图
      placeholder: 可在此粘贴图片
