import { RegionCodes, RegionLinks } from './regions'

const homePrefix = 'https://www.bilibili.com/'
const livePrefix = 'https://live.bilibili.com/'
/** 主站分区表 */
export const categories = {
  动画: {
    icon: 'douga',
    code: RegionCodes.anime,
    link: `${homePrefix}${RegionLinks.anime}`,
    subRegions: {
      MAD·AMV: `${homePrefix}${RegionLinks.anime}mad/`,
      MMD·3D: `${homePrefix}${RegionLinks.anime}mmd/`,
      短片·手书·配音: `${homePrefix}${RegionLinks.anime}voice/`,
      手办·模玩: `${homePrefix}${RegionLinks.anime}garage_kit/`,
      特摄: `${homePrefix}${RegionLinks.anime}tokusatsu/`,
      综合: `${homePrefix}${RegionLinks.anime}other/`,
    },
  },
  番剧: {
    icon: 'anime',
    code: RegionCodes.bangumi,
    link: `${homePrefix}${RegionLinks.bangumi}`,
    subRegions: {
      连载动画: `${homePrefix}v/anime/serial/`,
      完结动画: `${homePrefix}v/anime/finish/`,
      资讯: `${homePrefix}v/anime/information/`,
      官方延伸: `${homePrefix}v/anime/offical/`,
      新番时间表: `${homePrefix}anime/timeline/`,
      番剧索引: `${homePrefix}anime/index/`,
    },
  },
  国创: {
    icon: 'guochuang',
    code: RegionCodes.china,
    link: `${homePrefix}${RegionLinks.china}`,
    subRegions: {
      国产动画: `${homePrefix}v/guochuang/chinese/`,
      国产原创相关: `${homePrefix}v/guochuang/original/`,
      布袋戏: `${homePrefix}v/guochuang/puppetry/`,
      动态漫·广播剧: `${homePrefix}v/guochuang/motioncomic/`,
      资讯: `${homePrefix}v/guochuang/information/`,
      新番时间表: `${homePrefix}${RegionLinks.china}/timeline/`,
      国产动画索引: `${homePrefix}${RegionLinks.china}/index/`,
    },
  },
  音乐: {
    icon: 'music',
    code: RegionCodes.music,
    link: `${homePrefix}${RegionLinks.music}`,
    subRegions: {
      原创音乐: `${homePrefix}${RegionLinks.music}original/`,
      翻唱: `${homePrefix}${RegionLinks.music}cover/`,
      VOCALOID·UTAU: `${homePrefix}${RegionLinks.music}vocaloid/`,
      电音: `${homePrefix}${RegionLinks.music}electronic/`,
      演奏: `${homePrefix}${RegionLinks.music}perform/`,
      MV: `${homePrefix}${RegionLinks.music}mv/`,
      音乐现场: `${homePrefix}${RegionLinks.music}live/`,
      音乐综合: `${homePrefix}${RegionLinks.music}other/`,
      音频: `${homePrefix}audio/home?musicType=music`,
    },
  },
  舞蹈: {
    icon: 'dance',
    code: RegionCodes.dance,
    link: `${homePrefix}${RegionLinks.dance}`,
    subRegions: {
      宅舞: `${homePrefix}${RegionLinks.dance}otaku/`,
      街舞: `${homePrefix}${RegionLinks.dance}hiphop/`,
      明星舞蹈: `${homePrefix}${RegionLinks.dance}star/`,
      中国舞: `${homePrefix}${RegionLinks.dance}china/`,
      舞蹈综合: `${homePrefix}${RegionLinks.dance}three_d/`,
      舞蹈教程: `${homePrefix}${RegionLinks.dance}demo/`,
    },
  },
  游戏: {
    icon: 'game',
    code: RegionCodes.game,
    link: `${homePrefix}${RegionLinks.game}`,
    subRegions: {
      单机游戏: `${homePrefix}${RegionLinks.game}stand_alone/`,
      电子竞技: `${homePrefix}${RegionLinks.game}esports/`,
      手机游戏: `${homePrefix}${RegionLinks.game}mobile/`,
      网络游戏: `${homePrefix}${RegionLinks.game}online/`,
      桌游棋牌: `${homePrefix}${RegionLinks.game}board/`,
      GMV: `${homePrefix}${RegionLinks.game}gmv/`,
      音游: `${homePrefix}${RegionLinks.game}music/`,
      Mugen: `${homePrefix}${RegionLinks.game}mugen/`,
      游戏赛事: `${homePrefix}${RegionLinks.game}match/`,
    },
  },
  知识: {
    icon: 'technology',
    code: RegionCodes.tech,
    link: `${homePrefix}${RegionLinks.tech}`,
    subRegions: {
      科学科普: `${homePrefix}${RegionLinks.tech}science/`,
      社科人文: `${homePrefix}${RegionLinks.tech}fun/`,
      财经: `${homePrefix}${RegionLinks.tech}finance/`,
      校园学习: `${homePrefix}${RegionLinks.tech}campus/`,
      职业职场: `${homePrefix}${RegionLinks.tech}career/`,
      野生技术协会: `${homePrefix}${RegionLinks.tech}wild/`,
    },
  },
  数码: {
    icon: 'digital',
    code: RegionCodes.digital,
    link: `${homePrefix}${RegionLinks.digital}`,
    subRegions: {
      手机平板: `${homePrefix}${RegionLinks.digital}mobile/`,
      电脑装机: `${homePrefix}${RegionLinks.digital}pc/`,
      摄影摄像: `${homePrefix}${RegionLinks.digital}photography/`,
      影音智能: `${homePrefix}${RegionLinks.digital}intelligence_av/`,
    },
  },
  生活: {
    icon: 'life',
    code: RegionCodes.life,
    link: `${homePrefix}${RegionLinks.life}`,
    subRegions: {
      搞笑: `${homePrefix}${RegionLinks.life}funny/`,
      日常: `${homePrefix}${RegionLinks.life}daily/`,
      美食圈: `${homePrefix}${RegionLinks.life}food/`,
      动物圈: `${homePrefix}${RegionLinks.life}animal/`,
      手工: `${homePrefix}${RegionLinks.life}handmake/`,
      绘画: `${homePrefix}${RegionLinks.life}painting/`,
      运动: `${homePrefix}${RegionLinks.life}sports/`,
      汽车: `${homePrefix}${RegionLinks.life}automobile/`,
      其他: `${homePrefix}${RegionLinks.life}other/`,
    },
  },
  鬼畜: {
    icon: 'kichiku',
    code: RegionCodes.kichiku,
    link: `${homePrefix}${RegionLinks.kichiku}`,
    subRegions: {
      鬼畜调教: `${homePrefix}${RegionLinks.kichiku}guide/`,
      音MAD: `${homePrefix}${RegionLinks.kichiku}mad/`,
      人力VOCALOID: `${homePrefix}${RegionLinks.kichiku}manual_vocaloid/`,
      教程演示: `${homePrefix}${RegionLinks.kichiku}course/`,
    },
  },
  时尚: {
    icon: 'fashion',
    code: RegionCodes.fashion,
    link: `${homePrefix}${RegionLinks.fashion}`,
    subRegions: {
      美妆: `${homePrefix}${RegionLinks.fashion}makeup/`,
      服饰: `${homePrefix}${RegionLinks.fashion}clothing/`,
      健身: `${homePrefix}${RegionLinks.fashion}aerobics/`,
      T台: `${homePrefix}${RegionLinks.fashion}catwalk/`,
      风尚标: `${homePrefix}${RegionLinks.fashion}trends/`,
    },
  },
  资讯: {
    icon: 'information',
    code: RegionCodes.information,
    link: `${homePrefix}${RegionLinks.information}`,
    subRegions: {
      热点: `${homePrefix}${RegionLinks.information}/hotspot/`,
      环球: `${homePrefix}${RegionLinks.information}/global/`,
      社会: `${homePrefix}${RegionLinks.information}/social/`,
      综合: `${homePrefix}${RegionLinks.information}/multiple/`,
    },
  },
  娱乐: {
    icon: 'ent',
    code: RegionCodes.entertainment,
    link: `${homePrefix}${RegionLinks.entertainment}`,
    subRegions: {
      综艺: `${homePrefix}${RegionLinks.entertainment}/variety/`,
      明星: `${homePrefix}${RegionLinks.entertainment}/star/`,
      Korea相关: `${homePrefix}${RegionLinks.entertainment}/korea/`,
    },
  },
  影视: {
    icon: 'cinephile',
    code: RegionCodes.movie,
    link: `${homePrefix}${RegionLinks.movie}`,
    subRegions: {
      影视杂谈: `${homePrefix}${RegionLinks.movie}/cinecism/`,
      影视剪辑: `${homePrefix}${RegionLinks.movie}/montage/`,
      短片: `${homePrefix}${RegionLinks.movie}/shortfilm/`,
      预告·资讯: `${homePrefix}${RegionLinks.movie}/trailer_info/`,
    },
  },
  放映厅: {
    icon: 'cinema',
    code: [
      RegionCodes.documentary,
      RegionCodes.film,
      RegionCodes.tv,
    ],
    link: `${homePrefix}${RegionLinks.film}`,
    subRegions: {
      纪录片: `${homePrefix}documentary/`,
      电影: `${homePrefix}movie/`,
      电视剧: `${homePrefix}tv/`,
    },
  },
  专栏: { icon: 'read', code: null, link: `${homePrefix}read/home` },
  直播: {
    icon: 'zhibo',
    code: null,
    link: livePrefix,
    subRegions: {
      全部直播: `${livePrefix}all`,
      游戏直播: `${livePrefix}p/eden/area-tags?parentAreaId=2&areaId=0#/2/0`,
      手游直播: `${livePrefix}p/eden/area-tags?parentAreaId=3&areaId=0#/3/0`,
      娱乐直播: `${livePrefix}p/eden/area-tags?parentAreaId=1&areaId=0#/1/0`,
      电台直播: `${livePrefix}p/eden/area-tags?parentAreaId=5&areaId=0#/5/0`,
      绘画直播: `${livePrefix}p/eden/area-tags?parentAreaId=4&areaId=0#/4/0`,
    },
  },
  小黑屋: { icon: 'blackroom', code: null, link: `${homePrefix}blackroom/` },
  专题: { icon: 'topic', code: null, link: `${homePrefix}blackboard/topic_list.html` },
  活动: { icon: 'activit', code: null, link: `${homePrefix}blackboard/x/act_list` },
}
